# Generated by Django 5.2.7 on 2025-10-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trip_use_sleeper_berth'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='grid_positions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
