# Generated by Django 5.2.7 on 2025-10-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_logentry_grid_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('Off-Duty', 'Off-Duty'), ('Sleeper Berth', 'Sleeper Berth'), ('Driving', 'Driving'), ('On-Duty', 'On-Duty')], db_index=True, max_length=20),
        ),
    ]
