# Generated by Django 5.2.7 on 2025-10-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logentry_date_alter_logentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_location_coords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_coords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_coords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
